<?php

return [
    'defaults' => [
        'site_title' => 'Forum',
        'site_description' => 'Forum communautaire.',
        'footer_text' => 'Forum',
        'footer_link' => '',
        'stripe_enabled' => '0',
        'stripe_url' => '',
        'site_logo' => '',
        'site_favicon' => '',
        'site_footer_logo' => '',
        'theme_light_bg' => '#f6f4ef',
        'theme_light_surface' => '#ffffff',
        'theme_light_text' => '#1f2937',
        'theme_light_muted' => '#6b7280',
        'theme_light_primary' => '#d97706',
        'theme_light_accent' => '#0f766e',
        'theme_dark_bg' => '#0e1111',
        'theme_dark_surface' => '#151a1b',
        'theme_dark_text' => '#e5e7eb',
        'theme_dark_muted' => '#9ca3af',
        'theme_dark_primary' => '#f59e0b',
        'theme_dark_accent' => '#14b8a6',
        'theme_font' => '"Inter", system-ui, sans-serif',
        'theme_version' => '1',
    ],

    'presets' => [
        'amber_teal' => [
            'label' => 'Ambre / Sarcelle',
            'colors' => [
                'theme_light_bg' => '#f6f4ef',
                'theme_light_surface' => '#ffffff',
                'theme_light_text' => '#1f2937',
                'theme_light_muted' => '#6b7280',
                'theme_light_primary' => '#d97706',
                'theme_light_accent' => '#0f766e',
                'theme_dark_bg' => '#0e1111',
                'theme_dark_surface' => '#151a1b',
                'theme_dark_text' => '#e5e7eb',
                'theme_dark_muted' => '#9ca3af',
                'theme_dark_primary' => '#f59e0b',
                'theme_dark_accent' => '#14b8a6',
                'theme_font' => '"Inter", system-ui, sans-serif',
            ],
        ],
        'slate_mint' => [
            'label' => 'Ardoise / Menthe',
            'colors' => [
                'theme_light_bg' => '#f3f4f6',
                'theme_light_surface' => '#ffffff',
                'theme_light_text' => '#111827',
                'theme_light_muted' => '#6b7280',
                'theme_light_primary' => '#334155',
                'theme_light_accent' => '#10b981',
                'theme_dark_bg' => '#0b1220',
                'theme_dark_surface' => '#111827',
                'theme_dark_text' => '#e5e7eb',
                'theme_dark_muted' => '#9ca3af',
                'theme_dark_primary' => '#475569',
                'theme_dark_accent' => '#34d399',
                'theme_font' => '"Inter", system-ui, sans-serif',
            ],
        ],
        'sand_rose' => [
            'label' => 'Sable / Rose',
            'colors' => [
                'theme_light_bg' => '#f8f5f0',
                'theme_light_surface' => '#ffffff',
                'theme_light_text' => '#292524',
                'theme_light_muted' => '#78716c',
                'theme_light_primary' => '#ea580c',
                'theme_light_accent' => '#be185d',
                'theme_dark_bg' => '#140f10',
                'theme_dark_surface' => '#1f1618',
                'theme_dark_text' => '#f3f4f6',
                'theme_dark_muted' => '#a8a29e',
                'theme_dark_primary' => '#fb7185',
                'theme_dark_accent' => '#f472b6',
                'theme_font' => '"Inter", system-ui, sans-serif',
            ],
        ],
    ],

    // Les badges par défaut et leurs règles d'attribution vivent désormais dans
    // database/seeders/BadgeSeeder.php et dans la table `badges` (colonnes rule_type/rule_value),
    // éditables depuis /admin/badges. Voir App\Models\Badge::ruleTypes().
];
