<?php

return [
    'defaults' => [
        'site_title' => 'Forum',
        'site_description' => 'Forum communautaire.',
        'footer_text' => 'Forum',
        'footer_link' => '',
        'stripe_enabled' => '0',
        'stripe_url' => '',
        'theme_light_bg' => '#f6f4ef',
        'theme_light_surface' => '#ffffff',
        'theme_light_text' => '#1f2937',
        'theme_light_muted' => '#6b7280',
        'theme_light_primary' => '#d97706',
        'theme_light_accent' => '#0f766e',
        'theme_dark_bg' => '#0e1111',
        'theme_dark_surface' => '#151a1b',
        'theme_dark_text' => '#e5e7eb',
        'theme_dark_muted' => '#9ca3af',
        'theme_dark_primary' => '#f59e0b',
        'theme_dark_accent' => '#14b8a6',
        'theme_font' => '"Inter", system-ui, sans-serif',
        'theme_version' => '1',
    ],

    'presets' => [
        'amber_teal' => [
            'label' => 'Ambre / Sarcelle',
            'colors' => [
                'theme_light_bg' => '#f6f4ef',
                'theme_light_surface' => '#ffffff',
                'theme_light_text' => '#1f2937',
                'theme_light_muted' => '#6b7280',
                'theme_light_primary' => '#d97706',
                'theme_light_accent' => '#0f766e',
                'theme_dark_bg' => '#0e1111',
                'theme_dark_surface' => '#151a1b',
                'theme_dark_text' => '#e5e7eb',
                'theme_dark_muted' => '#9ca3af',
                'theme_dark_primary' => '#f59e0b',
                'theme_dark_accent' => '#14b8a6',
                'theme_font' => '"Inter", system-ui, sans-serif',
            ],
        ],
        'slate_mint' => [
            'label' => 'Ardoise / Menthe',
            'colors' => [
                'theme_light_bg' => '#f3f4f6',
                'theme_light_surface' => '#ffffff',
                'theme_light_text' => '#111827',
                'theme_light_muted' => '#6b7280',
                'theme_light_primary' => '#334155',
                'theme_light_accent' => '#10b981',
                'theme_dark_bg' => '#0b1220',
                'theme_dark_surface' => '#111827',
                'theme_dark_text' => '#e5e7eb',
                'theme_dark_muted' => '#9ca3af',
                'theme_dark_primary' => '#475569',
                'theme_dark_accent' => '#34d399',
                'theme_font' => '"Inter", system-ui, sans-serif',
            ],
        ],
        'sand_rose' => [
            'label' => 'Sable / Rose',
            'colors' => [
                'theme_light_bg' => '#f8f5f0',
                'theme_light_surface' => '#ffffff',
                'theme_light_text' => '#292524',
                'theme_light_muted' => '#78716c',
                'theme_light_primary' => '#ea580c',
                'theme_light_accent' => '#be185d',
                'theme_dark_bg' => '#140f10',
                'theme_dark_surface' => '#1f1618',
                'theme_dark_text' => '#f3f4f6',
                'theme_dark_muted' => '#a8a29e',
                'theme_dark_primary' => '#fb7185',
                'theme_dark_accent' => '#f472b6',
                'theme_font' => '"Inter", system-ui, sans-serif',
            ],
        ],
    ],

    'badges' => [
        ['name' => 'Fondateur', 'code' => 'founder', 'icon' => 'founder.png', 'color' => '#4f8cff'],
        ['name' => 'Admin', 'code' => 'admin', 'icon' => 'admin.png', 'color' => '#ff4d4f'],
        ['name' => 'Modérateur', 'code' => 'moderator', 'icon' => 'moderator.png', 'color' => '#7c5cff'],
        ['name' => 'Contributeur', 'code' => 'contributor', 'icon' => 'contributor.png', 'color' => '#16a34a'],
        ['name' => 'Premier message', 'code' => 'starter', 'icon' => 'starter.png', 'color' => '#4f8cff'],
        ['name' => '10 messages', 'code' => 'writer', 'icon' => 'writer.png', 'color' => '#00d1b2'],
        ['name' => '25 messages', 'code' => 'speaker', 'icon' => 'speaker.png', 'color' => '#ffb020'],
        ['name' => '50 messages', 'code' => 'veteran', 'icon' => 'veteran.png', 'color' => '#7c5cff'],
        ['name' => 'Premier sujet', 'code' => 'first_topic', 'icon' => 'first_topic.png', 'color' => '#ff4d4f'],
        ['name' => '10 sujets', 'code' => 'topics_10', 'icon' => 'topics_10.png', 'color' => '#ff4d4f'],
        ['name' => 'Donateur', 'code' => 'donator', 'icon' => 'donator.png', 'color' => '#00c2ff'],
    ],

    // Règles d'attribution automatique des badges liés à l'activité.
    'badge_rules' => [
        'starter' => ['min_posts' => 1, 'min_topics' => 0],
        'writer' => ['min_posts' => 10, 'min_topics' => 0],
        'speaker' => ['min_posts' => 25, 'min_topics' => 0],
        'veteran' => ['min_posts' => 50, 'min_topics' => 0],
        'first_topic' => ['min_posts' => 0, 'min_topics' => 1],
        'topics_10' => ['min_posts' => 0, 'min_topics' => 10],
        'contributor' => ['min_posts' => 5, 'min_topics' => 1],
    ],
];
